"""
Django settings for gymhealthapi project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from oauthlib.common import CLIENT_ID_CHARACTER_SET

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(1l%j4%y4fh85m2u%(!!dzn=)d1=pf#y$v%f57iq=pv#x*-9x+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition
CKEDITOR_UPLOAD_PATH = "images/"
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gymhealth.apps.GymhealthConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders',
]




# settings.py
VNPAY_CONFIG = {
    'TMN_CODE': '643RJMBQ',
    'HASH_SECRET': 'V3025B1XYEAPJFBN9FSXWEXIC52YRTMM',  # ✔ Đúng theo email
    'URL': 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html',
    'API_URL': 'https://sandbox.vnpayment.vn/merchant_webapi/api/transaction',
    'RETURN_URL': 'https://8983-171-231-61-11.ngrok-free.app/api/payments/vnpay/return/',
    'IPN_URL': 'https://8983-171-231-61-11.ngrok-free.app/api/payments/vnpay/ipn/',
    'VERSION': '2.1.0',
    'COMMAND': 'pay',
    'CURR_CODE': 'VND',
    'LOCALE': 'vn',
}


MOMO_CONFIG = {
    'ENDPOINT': 'https://test-payment.momo.vn/v2/gateway/api/create',
    'ACCESS_KEY': 'F8BBA842ECF85',
    'SECRET_KEY': 'K951B6PE1waDMi640xX08PD3vg6EkVlz',
    'PARTNER_CODE': 'MOMO',
    'PARTNER_NAME': 'MoMo Payment',
    'STORE_ID': 'Test Store',
    'REQUEST_TYPE': 'payWithMethod',
    'AUTO_CAPTURE': True,
    'LANG': 'vi',
    # URLs callback
    'REDIRECT_URL': 'https://cc89-171-231-61-11.ngrok-free.app/api/payments/momo/return/',
    'IPN_URL': 'https://cc89-171-231-61-11.ngrok-free.app/api/payments/momo/ipn/',
}
import os
# Thêm logging chi tiết hơn
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'vnpay.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'vnpay': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,

        },
    },
}
CELERY_BROKER_URL = 'redis://localhost:6379/0'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('oauth2_provider.contrib.rest_framework.OAuth2Authentication',)
}


# settings.py - Cấu hình Celery

CCELERY_BEAT_SCHEDULE = {
    'send-session-reminders': {
        'task': 'tasks.notification_tasks.send_session_reminders',
        'schedule': 60.0,  # Chạy mỗi phút
    },
    'send-expiry-reminders': {
        'task': 'tasks.notification_tasks.send_expiry_reminders',
        'schedule': 3600.0,  # Chạy mỗi giờ
    },
}

# Cấu hình email
EMAIL_NOTIFICATIONS_ENABLED = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'Gym Management System <your-email@gmail.com>'


# Thông tin gym
GYM_NAME = 'Your Gym Name'
GYM_ADDRESS = 'Địa chỉ phòng gym của bạn'

CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'


import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url

# Configuration
cloudinary.config(
    cloud_name="duqln52pu",
    api_key="924291448136996",
    api_secret="JdsaVdMKR25NG7w-VRIBB7H2WXk",  # Click 'View API Keys' above to copy your API secret
    secure=True
)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'gymhealthapi.middleware.VNPayCORSMiddleware'
]
AUTH_USER_MODEL = 'gymhealth.User'

import pymysql
ALLOWED_HOSTS=['*']
CSRF_TRUSTED_ORIGINS = [
    'https://sandbox.vnpayment.vn',
    'https://8983-171-231-61-11.ngrok-free.app/',  # URL ngrok hiện tại
    'https://sandbox.vnpayment.vn/vnpaygw-sit-testing/order',
]
pymysql.install_as_MySQLdb()
ROOT_URLCONF = 'gymhealthapi.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "gymhealth/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gymhealthapi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gymhealthdb',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': ''  # mặc định localhost
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}

CLIENT_ID = 'AybXSAZ8adNhzo3rKcuzxhnts15OmhSsoXzWinQh'
CLIENT_SECRET = '89c3eyIkMYEOboVb79WKxMsuixsRwptPUJwpBzc671UuMMom8ep05xruWHR8SeP63fvRBlPgLTu6H6yWhFveKNWCwkamMXWQN4iSEyfHhfYyPMyVjHvh7JI9nj7u355o'


