# Generated by Django 5.2 on 2025-04-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymhealth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='icon',
        ),
    ]
