# Generated by Django 5.2 on 2025-04-15 11:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymhealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
