# Generated by Django 5.2 on 2025-04-23 16:40

import gymhealth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymhealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', gymhealth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
