# Generated by Django 5.2 on 2025-06-13 03:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymhealth', '0002_payment_vnpay_transaction_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1749786536/jhhd6f0e2xe7wiynoplk.jpg', max_length=255),
        ),
    ]
